version: "3.9"

services:

  mongodb:
    image: mongo:5.0.9
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ADMIN_USER_NAME
      MONGO_INITDB_ROOT_PASSWORD: ADMIN_PASS
    volumes:
      - type: volume
        source: mongoData
        target: /data/db
      - type: bind
        source: /home/szilex94/.development/mongoDB
        target: /data/db

volumes:
  mongoData:
    name: mongo-DB-data
